### PR TITLE
sent $100000 for @uvhw with [14ZChL5niXVKFuVuF8JDc4ikqoEeehrFbC](bitcoin:14ZChL5niXVKFuVuF8JDc4ikqoEeehrFbC)

### PR DESCRIPTION
**Pull request by richerandprettier**

### CODE REVIEW

**Comment by richerandprettier** [comment]
> sent $100000 for @uvhw with [14ZChL5niXVKFuVuF8JDc4ikqoEeehrFbC](bitcoin:14ZChL5niXVKFuVuF8JDc4ikqoEeehrFbC)

**Comment by richerandprettier** [comment]
> No description provided.

#6

**Comment by richerandprettier** [comment]
#5

**Review by uvhw — CHANGES_REQUESTED** [review]
#11 _github-challenge-Bitcoin-Foundations-organization

**Comment by uvhw** [comment]
> No description provided.
response.api_address

**Pull request merged**
